### ISSUE TITLE
Breaks vim-flow

### ISSUE THREAD

**Issue by bouk** [mxw/vim-jsx#103]
I tried to get `vim-flow` working with `vim-jsx` but there doesn't seem to be an obvious way. I have:

* `let g:jsx_ext_required = 0`
* `let g:javascript_plugin_flow = 1`

When I open a JS file, for `set omnifunc?` I get `omnifunc=javascriptcomplete#CompleteJS`. Disabling `vim-jsx` fixes this.

This is the plugin order in my vimrc:

```
Plug 'facebook/vim-flow'                               
Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
Plug 'pangloss/vim-javascript'                         
Plug 'mxw/vim-jsx'
```

**Comment by mxw** [comment]
I'm not sure in what way this is "breaking" vim-flow.  Is it just that you expect a different omnifunc?  Are you sure that your plugin manager respects order-of-inclusion?  (Pathogen, e.g., uses alphabetical order.)

**Comment by bouk** [comment]
Yes, `vim-flow` is supposed to set the `omnifunc` to `flowcomplete#Complete`: https://github.com/flowtype/vim-flow/blob/10f7461c541ccdd9bf7ab59aace952f8c8b63cd7/after/ftplugin/javascript.vim#L19

I'm actually not sure whether my plugin manager cares about order-of-inclusion. What do you think could be overwriting `omnifunc` at a later point? I am not too familiar with how Vim(script) works, but I assume that setting `filetype` to `javascript.jsx` should still properly vim-flow's ftplugin

**Comment by mxw** [comment]
If you modify vim-flow locally so that after/ftplugin/javascript.jsx.vim is a copy of after/ftplugin/javascript.vim, does that fix the problem?

**Comment by bouk** [comment]
Actually I've figured it out, it seems that when `vim-jsx` does `filetype=javascript.jsx`, it re-initializes the ftplugins, which means that the omnifunc gets set to the default again. vim-flow has a thing to make sure its ftplugin only runs once however, so it won't overwrite the new omnifunc value

**Comment by bouk** [comment]
Here's the fix for vim-flow: https://github.com/flowtype/vim-flow/pull/31 thanks for the help!

**Comment by mxw** [comment]
Ah yeah—nice catch!  I think this might be the cause of a conflict with a completely unrelated package as well... thanks!

**Comment by pdf** [comment]
Seems like it would be better if vim-jsx didn't mess with the filetype at all, otherwise these issues are likely to crop up with other plugins that expect `filetype=javascript`.

**Comment by mxw** [comment]
Disagreed.  "JavaScript with JSX" is not the same syntax as "JavaScript", so its filetype should not be the same.  In particular, this is one of the cleanest ways to ensure that `vim-jsx` doesn't get loaded when you're editing normal, non-JSX files, since syntax highlighting is commonly used as a way of rudimentary syntax validation (and I'm philosophically on board with that use case).  If I were editing some CSS, I wouldn't want SCSS highlighting—likewise with C and C++, even though these all have superset relations as far as syntax goes.

I'm not sure how ftplugin guards are typically written... hopefully they're somewhat more robust to this in general, especially if they're in `after/` and expect to be overriding something (the user can always trigger a manual reload, after all).

**Comment by bouk** [comment]
Yeah the way this works fits in well with how vim highlighting seems to work, in that you can have nested syntaxes (like .html.erb)
