### ISSUE TITLE
Last prop in tag is not does not get correct color

### ISSUE THREAD

**Issue by blacksails** [mxw/vim-jsx#127]
I would expect the props to get the same colors in the following example.

![screen shot 2017-01-27 at 09 29 49](https://cloud.githubusercontent.com/assets/3807831/22364677/6b02ab1a-e473-11e6-9c15-2a692a9b2c39.png)

**Comment by mxw** [comment]
What are props in this context?  I thought tags could only have `foo=...` attributes; am I wrong or outdated?

**Comment by blacksails** [comment]
Hehe wether to call attributes props or attributes is a bit confusing to me in react. The receiving component has access to the attributes through props but in traditional html terminology it should indeed be called attributes.

An example of a standard HTML5 attribute which isen't on the `foo=...` form is `<button disabled>Disabled button</button>`

See this small example that shows it works in jsx/react aswell: https://codesandbox.io/s/Z6LkLp6ZQ

**Comment by mxw** [comment]
Ah, yeah, shows what I know about HTML...

This issue is inherited from the builtin XML syntax package.  If you do:

```
<div prop1 prop2></div>
```

you'll have this problem.  You can work around it with

```
<div prop1 prop2 ></div>
```

(note the whitespace).  You could also put the `attr=` attributes after.

Since this is an issue (or feature?) of the XML syntax package, it's outside the scope of vim-jsx.  Closing out the issue, but thanks for the report.
