### ISSUE TITLE
Some code is XMLified when it shouldn't be

### ISSUE THREAD

**Issue by kirjavascript** [mxw/vim-jsx#137]
using vim-plug and pangloss/vim-javascript

correct formatting;

![correct](http://i.imgur.com/QG75vFA.png)

here's the issue, the text variable is turned into an XML tag;

![issue](http://i.imgur.com/8Pt5w0u.png)

alternative colours;

![alt](http://i.imgur.com/CQVpzNn.png)

minimal .vimrc;

    call plug#begin('~/.vim/plugged')
    
    Plug 'pangloss/vim-javascript'
    Plug 'mxw/vim-jsx'
    
    call plug#end()

    let g:jsx_ext_required = 0

**Comment by mxw** [comment]
This is a known issue.  Syntax detection in vim is done via regular expressions, so it'll never be able to capture the full grammar of any sufficiently complex language.  In the case of JSX, we have to detect strings like `<this` as the start of an XML tag in order to switch into XML mode to highlight attributes and such, which means that certain whitespace choices are forbidden.

Some might consider this a feature, not a bug ;)
