### ISSUE TITLE
Indentation broken

### ISSUE THREAD

**Issue by wesleytodd** [mxw/vim-jsx#23]
Previous to including this plugin, my indentation worked "as expected", meaning in a reasonably and only semi-broken way.  After including this I get no auto-indentation.  For example, if I start with this:

```javascript
var a = React.createClass({
     render: function() {
         return (
             <div>[CURSOR HERE]
         );
     }
});
```

When I type enter/return I get this:

```javascript
var a = React.createClass({
     render: function() {
         return (
<div>
    [CURSOR HERE]
         );
     }
});
```

Without this plugin my vim configuration handles the indentation in a sane way and just doesn't have hilighting.  I would love to use this if this gets resolved, and alas I am no vim programmer or I would try to help out.

**Comment by mxw** [comment]
I am unable to repro this.  Usually indentation issues arise because you aren't using @pangloss's javascript plugin as the install instructions stipulate.  If you are, this is probably because of a conflict with some other plugin—feel free to link me to your .vimrc if you can't figure it out, but before you do so, please try to remove plugins until you figure out a minimal conflicting set.

**Comment by wesleytodd** [comment]
That was absolutely it.  Thanks for the help!

I didn't read that part of the readme, maybe moving it under installation would help?  I read that and usage because I assumed that any important information would be there.  Just a thought, feel free to ignore it....
