### ISSUE TITLE
Possible highlighting issue

### ISSUE THREAD

**Issue by joshacheson** [mxw/vim-jsx#28]
Hi there. I've installed this plugin and also its dependency via vundle. In some cases it seems to work just fine but I'm curious about two things.

1) In this case, would it be expected that the closing div is highlighted in a different color than the opening div?

![screen shot 2015-02-05 at 12 04 36 pm](https://cloud.githubusercontent.com/assets/1906888/6064916/38c6f25a-ad2f-11e4-9d3b-0d7f769d6dca.png)

2) If I add an opening quote to the content of my element, highlighting seems to go awry.

![screen shot 2015-02-05 at 12 05 41 pm](https://cloud.githubusercontent.com/assets/1906888/6064928/54699d46-ad2f-11e4-8b3d-6912f6cbfca3.png)

I can't be 100% sure if this is just an issue of improper installation or if these are features/problems inherent to this plugin.

**Comment by joshacheson** [comment]
Note: After changing my color scheme in VIM, i'm finding that my first point was just a problem with my colorscheme. For what ever reason tomorrow night doesn't handle jsx so well.

The other issue, regarding open quotes, exists with each color scheme I try though.

**Comment by mxw** [comment]
Yeah, I see this also.  It might be a wontfix, though—The xmlRegion needs to support embedding jsStrings because you're allowed to have bare strings as children (and bare words just get picked up as strings stripped of leading/trailing whitespace, IIRC).  The XML syntax package doesn't have a syntax class for bare words; it's just "nothing", so it's hard to prevent the matchers from picking up strings that start in the middle of such an extent.

If I come up with a solution, I'll commit it, but otherwise, you can always work around this by just quoting your string.

**Comment by milieu** [comment]
Also have the same problem, and I installed via Vundle too. Using the [vim--colors-solarized](https://github.com/altercation/vim-colors-solarized) plugin as my color scheme.

**Comment by mxw** [comment]
Not workin' on this presently.  If you come up with something, let's talk pull requests.  Hopefully the double-quoting workaround isn't too bad.
