### ISSUE TITLE
Interest in Vim JSX compilation support?

### ISSUE THREAD

**Issue by mrjamesriley** [mxw/vim-jsx#41]
Hi all,

One feature I enjoyed and benefitted from when starting out with CoffeeScript, was the [vim-coffee-script](https://github.com/kchmck/vim-coffee-script) plugin, which provides the ability to easily 'preview' the compiled Javascript while working in Vim, as a means of debugging and learning. 

I've put together a working example of how this could work for JSX, which can be found here: https://github.com/mrjamesriley/jsx-compiler-vim - it works by calling out to the system, to run a JS script which in turns compiles the passed in JSX using the official `react-tools`, returning the compiled JS, before outputting this into a new buffer within Vim. The middle-man step of a JS script seems necessary here given that the npm `jsx` does not seem to support standard steams.

I'm relatively new to VimL, but enjoying the process - is there interest in having `vim-jsx` provide such functionality? I'd happily put the time in to get this functionality added to this plugin - what do you think?

cheers,
James

**Comment by mxw** [comment]
Sorry for the unconscionably long response time...

I have a instinctive reluctance towards having a single vim package (or, more generally, any module for any purpose) do too much work.  Having filetype detection, syntax highlighting, and indentation all in one place is necessary, because they largely depend on one another (ftdetect -> syntax -> indent), but in-editor compilation is a different beast.

I personally stay away from IDE-like features in vim, and so I prefer my packages small and lightweight.  But, I'm sure there are members of the community who would appreciate an in-editor code transformer—and it needn't be part of this particular repo to be useful (although I did stake an early claim with regard to repo name...).

You should try pinging the React team to see if they can give you better streaming support to make a better in-editor compilation experience.

Sorry again for the delay, and good luck if you're still planning to work on this :D
