### ISSUE TITLE
Apostrophes not supported?

### ISSUE THREAD

**Issue by kendagriff** [mxw/vim-jsx#46]
Syntax gets goofed up when using apostrophes:

![screen shot 2015-05-19 at 11 32 54 am](https://cloud.githubusercontent.com/assets/110935/7709524/e45a225e-fe1a-11e4-9cbc-5a8404a2a671.png)

**Comment by tecfu** [comment]
How about when you escape the apostrophe as in 

```
<Header> You\'s is my name.</Header>
```

**Comment by kendagriff** [comment]
![screen shot 2015-05-20 at 6 39 18 am](https://cloud.githubusercontent.com/assets/110935/7725802/0b84381a-febb-11e4-8c14-1c03a5283587.png)

Still the same. Perhaps it's a plugin conflict?

**Comment by mxw** [comment]
Just double-quote the whole raw string.  Handling raw strings with single quotes is unsupported at present.

**Comment by richardfickling** [comment]
Sorry, why was this closed? Double-quoting the raw string would cause the double quotes to appear in the final HTML. You said it's "unsupported at present" - isn't that exactly why you'd want to keep it open?

**Comment by mxw** [comment]
@richardfickling—When I implemented the syntax file, I pointedly made it so that quoted strings were highlighted as JS strings when they were the children of JSX nodes.  I _think_ it used to be the case that string literal children would be interpreted as string literals, rather than having their surrounding quotes escaped and made part of the string... either this was never the case, or it is no longer the case.

Supporting both string-literals-as-children and quotes-embedded-in-bare-strings was a wontfix, but since the former is no longer correct, the fix is easy—I'll have it up shortly.

**Comment by davidjb** [comment]
Seeing the same results (with the latest `master`) as @kendagriff's screenshots when apostrophe characters are used -- could this be reopened?

**Comment by mxw** [comment]
Whoops, I didn't actually mean to reopen this.  I can't repro; can you read the README and then take the outlined steps?

**Comment by davidjb** [comment]
Sorry for the noise, it was a conflict between setting filetype; my vimrc set it and `vim-jsx` sets it too.
